[package]
name = "kvs"
version = "0.1.0"
authors = ["Chris Wren <chriswrendeveloper@gmail.com>"]
description = "A key-value store"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
structopt = "0.3"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
